# Generated by Django 5.0.6 on 2026-05-19 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LineUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("福岡", "福岡"),
                            ("熊本", "熊本"),
                            ("長崎", "長崎"),
                            ("佐賀", "佐賀"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("step", models.CharField(default="none", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LineLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "text"), ("location", "location")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkapp.lineuser",
                    ),
                ),
            ],
        ),
    ]
