# Generated by Django 5.0.6 on 2026-07-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineuser",
            name="sender",
            field=models.CharField(default="USER", max_length=10),
        ),
    ]
