# Generated by Django 5.0.6 on 2026-07-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkapp", "0002_lineuser_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineuser",
            name="sender",
        ),
        migrations.AddField(
            model_name="linelog",
            name="sender",
            field=models.CharField(default="USER", max_length=10),
        ),
    ]
