# Generated by Django 5.0.6 on 2026-07-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkapp", "0003_remove_lineuser_sender_linelog_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
