# Generated by Django 5.0.6 on 2026-07-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkapp", "0004_lineuser_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("北九州", "北九州"),
                            ("福岡", "福岡"),
                            ("大分", "大分"),
                            ("熊本", "熊本"),
                            ("長崎", "長崎"),
                            ("佐世保", "佐世保"),
                        ],
                        max_length=20,
                    ),
                ),
                ("login_id", models.CharField(max_length=6, unique=True)),
                ("birth_date", models.DateField()),
                ("password", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
