# Generated by Django 5.0.6 on 2026-08-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkapp", "0005_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineuser",
            name="login_id",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
