# Generated by Django 5.0.6 on 2026-08-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkapp", "0006_lineuser_login_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
