# Generated by Django 5.0.6 on 2026-08-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkapp", "0007_broadcasthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcasthistory",
            name="pdf_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
