# Generated by Django 5.0.6 on 2026-08-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkapp", "0008_broadcasthistory_pdf_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnionNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("pdf_filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
