# Generated by Django 5.0.6 on 2026-08-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkapp", "0009_unionnews"),
    ]

    operations = [
        migrations.AddField(
            model_name="unionnews",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
