# Generated by Django 5.0.6 on 2026-09-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0010_unionnews_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('weekday', models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], default=0)),
                ('send_time', models.TimeField(default='08:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
