# Generated by Django 5.0.6 on 2026-09-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0011_healthcheckschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckschedule',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
