# Generated by Django 5.0.6 on 2026-05-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineuser",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lineuser",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
